server:
  port: 8761

eureka:
  instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${random.uuid}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/