server:
  port: 9411

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/