spring:
  application:
      name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configration
  profiles:
     active: native

server:
  port: 8888